services:
  canon-printer:
    build: .
    container_name: canon-printer
    restart: always
    ports:
      - "631:631"
    security_opt:
      - "label=disable"
    devices:
      - "/dev/bus/usb/001/002:/dev/bus/usb/001/002"